etherscan:
  selenium:
    remoteWebDriverUrl: http://selenium:4444
bot:
  token: 5585724218:AAGvPZFL2tGu-GOhYMBnHO4nWvstgkLwqqM
  username: etherscan_script_bot
spring:
  web:
    resources:
     static-locations[0]: file:src/main/resources/static/
     static-locations[1]: classpath:/static/
# ==============================================================
# = Data Source
# ==============================================================
  datasource:
    url: jdbc:mysql://mysql:3306/etherscan?useSSL=true&characterEncoding=utf-8&serverTimezone=Europe/Kiev&useLegacyDatetimeCode=false
    username: root
    password: siden123
    driverClassName: com.mysql.cj.jdbc.Driver
    # ==============================================================
    # = Keep the connection alive if idle for a long time (needed in production)
    # ==============================================================
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      # ==============================================================
      # = Hibernate ddl auto (create, create-drop, update)
      # ==============================================================
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        # ==============================================================
        # = The SQL dialect makes Hibernate generate better SQL for the chosen database
        # ==============================================================
        dialect: org.hibernate.dialect.MySQL5Dialect
        jdbc.time_zone: Europe/Kiev
